FROM node:20-alpine

WORKDIR /app
EXPOSE 3000

# Copy root package files for caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install
RUN npm install -g tsx typescript

# Copy root tsconfig and lumoria-core
COPY tsconfig.json ./
COPY lumoria-core ./lumoria-core/

# Start the app
CMD ["npm", "run", "dev:core"]
